// Generates packages/core/src/maps/earthData.ts: the Earth land mask for the
// Earth mode, rasterised from Natural Earth 1:50m land polygons (public domain).
//
//   node packages/core/scripts/earth-mask.mjs [path/to/ne_50m_land.geojson]
//
// Without a path the GeoJSON is downloaded. Equirectangular, 0.25 degrees per
// cell: 1440 x 720 cells, column 0 at 180 W, row 0 at 90 N. A cell is land when
// its centre lies inside a land polygon (even-odd scanline fill). Continent
// outlines only: islands under MIN_ISLAND cells are dropped and lakes under
// MIN_LAKE cells are filled. The mask is stored row by row as run lengths
// (water first, alternating), LEB128 varints, base64.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const URL_50M = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_land.geojson';
const W = 1440;
const H = 720;
const STEP = 360 / W;
const MIN_ISLAND = 16;
const MIN_LAKE = 16;

const src = process.argv[2];
const geo = src ? JSON.parse(readFileSync(src, 'utf8')) : await (await fetch(URL_50M)).json();

const rings = [];
for (const f of geo.features) {
  const g = f.geometry;
  if (g.type === 'Polygon') rings.push(...g.coordinates);
  else if (g.type === 'MultiPolygon') for (const p of g.coordinates) rings.push(...p);
}

const land = new Uint8Array(W * H);
for (let row = 0; row < H; row++) {
  const lat = 90 - (row + 0.5) * STEP;
  const xs = [];
  for (const ring of rings) {
    for (let i = 0; i < ring.length - 1; i++) {
      const [lon0, lat0] = ring[i];
      const [lon1, lat1] = ring[i + 1];
      if (lat0 > lat === lat1 > lat) continue;
      xs.push(lon0 + ((lat - lat0) * (lon1 - lon0)) / (lat1 - lat0));
    }
  }
  xs.sort((a, b) => a - b);
  for (let i = 0; i + 1 < xs.length; i += 2) {
    const c0 = Math.max(0, Math.ceil((xs[i] + 180) / STEP - 0.5));
    const c1 = Math.min(W - 1, Math.ceil((xs[i + 1] + 180) / STEP - 0.5) - 1);
    for (let c = c0; c <= c1; c++) land[row * W + c] = 1;
  }
}

/** Flip connected components of `value` smaller than `min` cells (8-neighbour, wrapping east-west). */
function dropSmall(value, min) {
  const seen = new Uint8Array(W * H);
  let flipped = 0;
  for (let i = 0; i < W * H; i++) {
    if (seen[i] || land[i] !== value) continue;
    const comp = [i];
    seen[i] = 1;
    for (let j = 0; j < comp.length; j++) {
      const x = comp[j] % W;
      const y = (comp[j] - x) / W;
      for (let dy = -1; dy <= 1; dy++) {
        const ny = y + dy;
        if (ny < 0 || ny >= H) continue;
        for (let dx = -1; dx <= 1; dx++) {
          const n = ny * W + ((x + dx + W) % W);
          if (seen[n] || land[n] !== value) continue;
          seen[n] = 1;
          comp.push(n);
        }
      }
    }
    if (comp.length < min) {
      for (const n of comp) land[n] = 1 - value;
      flipped += comp.length;
    }
  }
  return flipped;
}
const islands = dropSmall(1, MIN_ISLAND);
const lakes = dropSmall(0, MIN_LAKE);

const bytes = [];
const varint = (n) => {
  while (n >= 0x80) {
    bytes.push((n & 0x7f) | 0x80);
    n >>>= 7;
  }
  bytes.push(n);
};
let landCells = 0;
for (let row = 0; row < H; row++) {
  let v = 0;
  let run = 0;
  for (let c = 0; c < W; c++) {
    const l = land[row * W + c];
    landCells += l;
    if (l === v) run++;
    else {
      varint(run);
      v = l;
      run = 1;
    }
  }
  varint(run);
}
const b64 = Buffer.from(bytes).toString('base64');

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../src/maps/earthData.ts');
const lines = b64.match(/.{1,120}/g).map((l) => `  '${l}'`).join(',\n');
writeFileSync(
  out,
  `// Generated by packages/core/scripts/earth-mask.mjs from Natural Earth 1:50m land (public domain). Do not edit.\n` +
    `// ${W} x ${H} cells, ${STEP} degrees each; ${landCells} land cells; ${islands} island cells dropped, ${lakes} lake cells filled.\n` +
    `export const EARTH_W = ${W};\nexport const EARTH_H = ${H};\n` +
    `/** Run lengths per row (water first, alternating), LEB128 varints, base64. */\nexport const EARTH_RLE = [\n${lines},\n].join('');\n`,
);
console.log(`${out}: ${landCells} land cells (${((100 * landCells) / (W * H)).toFixed(1)} %), ${b64.length} base64 chars, ${islands} island / ${lakes} lake cells flipped`);
